### ISSUE TITLE
Error with WebStorm 2019.3 EAP

### ISSUE THREAD

**Issue by wijskinner** [styled-components/webstorm-styled-components#72]
* **IDE name and version:** 
WebStorm 2019.3 EAP
Build #WS-193.2956.38, built on September 11, 2019
WebStorm EAP User
Expiration date: October 11, 2019
Runtime version: 11.0.4+12-b462.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-27-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 4062M
Cores: 4
Registry: 
Non-Bundled Plugins: 
* **Styled-components plugin version:** 
1.0.10

## Problem description:
An error occurs when attempting to type in some sections of styled components resulting in no output to the screen ie Typing doesn't work 

![image](https://user-images.githubusercontent.com/48635730/64856295-8ecf7d80-d619-11e9-8aac-cc38f248b2b3.png)

`java.lang.IllegalStateException
	at com.intellij.psi.impl.source.tree.injected.MultiHostRegistrarImpl.getResult(MultiHostRegistrarImpl.java:25)
	at com.intellij.styledComponents.StyledComponentsInjector.getInjectionResult(StyledComponentsInjector.kt:70)
	at com.intellij.styledComponents.StyledComponentsInjector.getLanguagesToInject(StyledComponentsInjector.kt:59)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:421)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.probeElementsUp(InjectedLanguageUtil.java:341)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:166)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.findInside(InjectedLanguageUtil.java:483)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.tryOffset(InjectedLanguageUtil.java:462)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.findInjectedElementNoCommit(InjectedLanguageUtil.java:442)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.findInjectedElementAt(InjectedLanguageManagerImpl.java:286)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.getInjectedFileIfAny(BraceHighlightingHandler.java:177)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.lambda$null$1(BraceHighlightingHandler.java:112)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1043)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:124)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:592)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:538)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:113)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.lambda$null$2(BraceHighlightingHandler.java:101)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:176)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.lambda$null$3(BraceHighlightingHandler.java:100)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1048)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.lambda$lookForInjectedAndMatchBracesInOtherThread$4(BraceHighlightingHandler.java:98)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:254)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by dancrumb** [comment]
Do you have a rough timeline for a release? I've downgraded to 2019.2 so that I can keep using your plugin, but hoping I'll be able to upgrade again soon...

**Comment by prigara** [comment]
Hi @dancrumb, WebStorm 2019.3 is going to be released in 2 months. The current stable WebStorm version is still 2019.2.

**Comment by sofiageo** [comment]
> Hi @dancrumb, WebStorm 2019.3 is going to be released in 2 months. The current stable WebStorm version is still 2019.2.

Hello, thanks for the plugin. I'm confused by your message though. It feels like punishing people for want to beta test your early access builds. Plus the idea-version of the plugin doesn't limit it to the stable builds, which actually breaks the IDEA gui at the moment. I had to remove the plugin for now unfortunately.

**Comment by dancrumb** [comment]
Yeah, I was using 2019.3 via the EAP. Right now I have to choose between 2019.3 or this plugin. I was just curious to know if there was a plugin release planned any time soon.

Or is the plan to release the plugin upgrade with 2019.3? If so, it's worth knowing that will push some people out of the EAP.

**Comment by prigara** [comment]
Sorry, I have misunderstood the question about the release: these are the dates for the IDE release. As for the release date for the styled-components plugin update that would contain the fix for WebStorm 2019.3, I can't provide the exact date at the moment - we'll try our best to look into the problem next week and publish a new plugin as soon as possible.

The Early Preview builds are less stable than the stable builds. We are actively implementing the changes and it can happen that some features can become less stable. Unfortunately, we can't always guarantee that plugins that are not part of the default IDE setup won't break. Sorry. As I've said, we'll look into the problem.

**Comment by dancrumb** [comment]
Thanks! I appreciate the info.

Looking forward to the fix because I love the new feature in 2019.3 and can't wait to get back to it!

Really appreciate all the work you folks are doing!!

**Comment by prigara** [comment]
Hi all, a new version of the plugin has been released: https://plugins.jetbrains.com/plugin/9997-styled-components
